### PR TITLE
Quynhbranch

### PR DESCRIPTION
**Pull request by qpham2594**
Updating colors of the button links

### CODE REVIEW

**Comment by qpham2594** [comment]
Also changed the hovering color feature of navigation where it changed the background to white and links to black on iPad and iPhone responsive screens

**Comment by qpham2594** [comment]
Also add my challenges to the ReadMe file

**Comment by qpham2594** [comment]
Retained 150px for web header, increased to 170px for iPad, and decreased to 110px for mobile

**Comment by qpham2594** [comment]
decreased content text from 20px to 15px

**Review by Seiraeurta31 — APPROVED** [review]

**Pull request merged**
